name: pl-hooks CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test for a successful build
    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - name: Install system dependencies
      run: sudo apt install -y unzip

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install deps
      working-directory: ./packages/pl-hooks
      run: yarn install --ignore-scripts

    - name: Lint
      working-directory: ./packages/pl-hooks
      run: yarn lint

    - name: build
      env:
        NODE_ENV: production
      working-directory: ./packages/pl-hooks
      run: yarn build
